-- LMPT2 SSCS cloud backend for Supabase
-- Run this file once in Supabase Dashboard > SQL Editor.
-- It creates Auth-linked profiles, vessel/study tables, RLS policies,
-- a private Storage bucket, and a small audit trail.

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Core tables
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text not null default '',
  company text not null default '',
  role text check (role in ('terminal_officer','ship_officer','viewer')),
  account_status text not null default 'pending' check (account_status in ('pending','approved','rejected')),
  is_admin boolean not null default false,
  registered_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_email_lower_idx on public.profiles (lower(email));

create table if not exists public.vessels (
  id bigint primary key generated by default as identity,
  name text not null,
  imo text not null,
  call_sign text,
  flag text,
  port_of_registry text,
  year_built integer,
  vessel_type text,
  capacity text,
  owner text,
  operator text,
  classification text,
  gas_mgmt_1 text,
  gas_mgmt_2 text,
  status text not null default 'Active',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists vessels_imo_lower_idx on public.vessels (lower(imo));
create index if not exists vessels_name_idx on public.vessels (name);

create table if not exists public.sscs_studies (
  id text primary key,
  vessel_id bigint not null references public.vessels(id) on delete restrict,
  vessel_name text not null,
  status text not null check (status in ('access_requested','access_rejected','draft','submitted','approved','edit_requested','editing')),
  initiated_by_id uuid not null references auth.users(id) on delete restrict,
  initiated_by_name text not null,
  initiated_by_role text check (initiated_by_role in ('terminal_officer','ship_officer','viewer')),
  initiated_at timestamptz not null default now(),
  submitted_at timestamptz,
  reviewed_by_id uuid references auth.users(id) on delete set null,
  reviewed_by_name text,
  approved_at timestamptz,
  edit_requested_by_id uuid references auth.users(id) on delete set null,
  edit_requested_by_name text,
  edit_requested_at timestamptz,
  items jsonb not null default '[]'::jsonb,
  ship_notes text not null default '',
  terminal_notes text not null default '',
  updated_at timestamptz not null default now()
);

create index if not exists sscs_studies_vessel_idx on public.sscs_studies(vessel_id);
create index if not exists sscs_studies_initiated_by_idx on public.sscs_studies(initiated_by_id);
create index if not exists sscs_studies_status_idx on public.sscs_studies(status);

create table if not exists public.study_sections (
  study_id text not null references public.sscs_studies(id) on delete cascade,
  section_key text not null,
  data jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key (study_id, section_key)
);

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  study_id text not null references public.sscs_studies(id) on delete cascade,
  document_type text not null,
  file_name text not null,
  storage_path text not null unique,
  mime_type text,
  file_size bigint,
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists documents_study_idx on public.documents(study_id);

create table if not exists public.audit_logs (
  id bigint primary key generated always as identity,
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_entity_idx on public.audit_logs(entity_type, entity_id);

-- ---------------------------------------------------------------------------
-- Auth profile creation
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  requested_role text;
begin
  requested_role := new.raw_user_meta_data->>'role';
  if requested_role not in ('terminal_officer','ship_officer','viewer') then
    requested_role := 'viewer';
  end if;

  insert into public.profiles (
    id, full_name, email, company, role, account_status, is_admin, registered_at, updated_at
  ) values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data->>'company', ''),
    requested_role,
    'pending',
    false,
    coalesce(new.created_at, now()),
    now()
  )
  on conflict (id) do update set
    full_name = excluded.full_name,
    email = excluded.email,
    company = excluded.company,
    role = excluded.role,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

-- Backfill profiles if Auth users already existed before this migration.
insert into public.profiles (id, full_name, email, company, role, account_status, is_admin, registered_at, updated_at)
select
  u.id,
  coalesce(u.raw_user_meta_data->>'full_name',''),
  coalesce(u.email,''),
  coalesce(u.raw_user_meta_data->>'company',''),
  case when u.raw_user_meta_data->>'role' in ('terminal_officer','ship_officer','viewer')
       then u.raw_user_meta_data->>'role' else 'viewer' end,
  'pending',
  false,
  coalesce(u.created_at, now()),
  now()
from auth.users u
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Security helper functions. SECURITY DEFINER avoids recursive profile RLS.
-- ---------------------------------------------------------------------------
create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce((select p.is_admin from public.profiles p where p.id = auth.uid()), false);
$$;

create or replace function public.current_user_is_approved()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce((select p.account_status = 'approved' from public.profiles p where p.id = auth.uid()), false);
$$;

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select (select p.role from public.profiles p where p.id = auth.uid());
$$;

create or replace function public.can_read_study(target_study_id text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.current_user_is_approved()
     and exists (select 1 from public.sscs_studies s where s.id = target_study_id);
$$;

create or replace function public.can_edit_study(target_study_id text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.sscs_studies s
    where s.id = target_study_id
      and public.current_user_is_approved()
      and (
        public.current_user_is_admin()
        or public.current_user_role() = 'terminal_officer'
        or (
          public.current_user_role() = 'ship_officer'
          and s.initiated_by_id = auth.uid()
          and s.status in ('draft','editing')
        )
      )
  );
$$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.vessels enable row level security;
alter table public.sscs_studies enable row level security;
alter table public.study_sections enable row level security;
alter table public.documents enable row level security;
alter table public.audit_logs enable row level security;

-- Profiles: users can always read themselves. Approved users can read the internal
-- directory because the application needs recipient names/emails for workflow notices.
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
for select to authenticated
using (id = auth.uid() or public.current_user_is_approved() or public.current_user_is_admin());

drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles
for update to authenticated
using (public.current_user_is_admin())
with check (public.current_user_is_admin());

-- Vessels
drop policy if exists vessels_select on public.vessels;
create policy vessels_select on public.vessels
for select to authenticated
using (public.current_user_is_approved() or public.current_user_is_admin());

drop policy if exists vessels_insert on public.vessels;
create policy vessels_insert on public.vessels
for insert to authenticated
with check (
  public.current_user_is_approved()
  and (
    public.current_user_is_admin()
    or public.current_user_role() in ('terminal_officer','ship_officer')
  )
  and (created_by is null or created_by = auth.uid())
);

drop policy if exists vessels_update on public.vessels;
create policy vessels_update on public.vessels
for update to authenticated
using (
  public.current_user_is_approved()
  and (
    public.current_user_is_admin()
    or public.current_user_role() = 'terminal_officer'
    or created_by = auth.uid()
  )
)
with check (
  public.current_user_is_approved()
  and (
    public.current_user_is_admin()
    or public.current_user_role() = 'terminal_officer'
    or created_by = auth.uid()
  )
);

drop policy if exists vessels_delete on public.vessels;
create policy vessels_delete on public.vessels
for delete to authenticated
using (public.current_user_is_admin());

-- Studies: all approved internal users may read. Viewer is read-only.
drop policy if exists studies_select on public.sscs_studies;
create policy studies_select on public.sscs_studies
for select to authenticated
using (public.current_user_is_approved() or public.current_user_is_admin());

drop policy if exists studies_insert on public.sscs_studies;
create policy studies_insert on public.sscs_studies
for insert to authenticated
with check (
  public.current_user_is_approved()
  and initiated_by_id = auth.uid()
  and (
    public.current_user_is_admin()
    or public.current_user_role() = 'terminal_officer'
    or (public.current_user_role() = 'ship_officer' and status in ('access_requested','draft'))
  )
);

drop policy if exists studies_terminal_update on public.sscs_studies;
create policy studies_terminal_update on public.sscs_studies
for update to authenticated
using (
  public.current_user_is_approved()
  and (public.current_user_is_admin() or public.current_user_role() = 'terminal_officer')
)
with check (
  public.current_user_is_approved()
  and (public.current_user_is_admin() or public.current_user_role() = 'terminal_officer')
);

drop policy if exists studies_ship_update on public.sscs_studies;
create policy studies_ship_update on public.sscs_studies
for update to authenticated
using (
  public.current_user_is_approved()
  and public.current_user_role() = 'ship_officer'
  and initiated_by_id = auth.uid()
  and status in ('draft','editing','approved')
)
with check (
  initiated_by_id = auth.uid()
  and status in ('draft','editing','submitted','edit_requested')
);

drop policy if exists studies_admin_delete on public.sscs_studies;
create policy studies_admin_delete on public.sscs_studies
for delete to authenticated
using (public.current_user_is_admin());

-- Study sections follow permissions of their parent study.
drop policy if exists sections_select on public.study_sections;
create policy sections_select on public.study_sections
for select to authenticated
using (public.can_read_study(study_id));

drop policy if exists sections_insert on public.study_sections;
create policy sections_insert on public.study_sections
for insert to authenticated
with check (public.can_edit_study(study_id));

drop policy if exists sections_update on public.study_sections;
create policy sections_update on public.study_sections
for update to authenticated
using (public.can_edit_study(study_id))
with check (public.can_edit_study(study_id));

drop policy if exists sections_delete on public.study_sections;
create policy sections_delete on public.study_sections
for delete to authenticated
using (public.can_edit_study(study_id) or public.current_user_is_admin());

-- Document metadata
drop policy if exists documents_select on public.documents;
create policy documents_select on public.documents
for select to authenticated
using (public.can_read_study(study_id));

drop policy if exists documents_insert on public.documents;
create policy documents_insert on public.documents
for insert to authenticated
with check (public.can_edit_study(study_id) and uploaded_by = auth.uid());

drop policy if exists documents_delete on public.documents;
create policy documents_delete on public.documents
for delete to authenticated
using (public.can_edit_study(study_id) or public.current_user_is_admin());

-- Audit logs are visible to admins and terminal officers; writes are made by triggers only.
drop policy if exists audit_logs_select on public.audit_logs;
create policy audit_logs_select on public.audit_logs
for select to authenticated
using (
  public.current_user_is_approved()
  and (public.current_user_is_admin() or public.current_user_role() = 'terminal_officer')
);

-- ---------------------------------------------------------------------------
-- Private Storage bucket and policies
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit)
values ('sscs-documents', 'sscs-documents', false, 52428800)
on conflict (id) do update set public = false, file_size_limit = 52428800;

drop policy if exists sscs_documents_select on storage.objects;
create policy sscs_documents_select on storage.objects
for select to authenticated
using (
  bucket_id = 'sscs-documents'
  and public.can_read_study(split_part(name, '/', 1))
);

drop policy if exists sscs_documents_insert on storage.objects;
create policy sscs_documents_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'sscs-documents'
  and public.can_edit_study(split_part(name, '/', 1))
);

drop policy if exists sscs_documents_update on storage.objects;
create policy sscs_documents_update on storage.objects
for update to authenticated
using (
  bucket_id = 'sscs-documents'
  and public.can_edit_study(split_part(name, '/', 1))
)
with check (
  bucket_id = 'sscs-documents'
  and public.can_edit_study(split_part(name, '/', 1))
);

drop policy if exists sscs_documents_delete on storage.objects;
create policy sscs_documents_delete on storage.objects
for delete to authenticated
using (
  bucket_id = 'sscs-documents'
  and (public.can_edit_study(split_part(name, '/', 1)) or public.current_user_is_admin())
);

-- ---------------------------------------------------------------------------
-- Protect fields and workflow transitions for ship officers even if a browser
-- client is tampered with. Terminal officers/admins are governed by their RLS.
-- ---------------------------------------------------------------------------
create or replace function public.enforce_ship_study_update()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if public.current_user_role() = 'ship_officer' and not public.current_user_is_admin() then
    if new.initiated_by_id is distinct from old.initiated_by_id
       or new.initiated_by_name is distinct from old.initiated_by_name
       or new.initiated_by_role is distinct from old.initiated_by_role
       or new.vessel_id is distinct from old.vessel_id
       or new.vessel_name is distinct from old.vessel_name
       or new.terminal_notes is distinct from old.terminal_notes
       or new.reviewed_by_id is distinct from old.reviewed_by_id
       or new.reviewed_by_name is distinct from old.reviewed_by_name
       or new.approved_at is distinct from old.approved_at then
      raise exception 'Ship officers cannot modify protected study fields';
    end if;

    if not (
      (old.status = 'draft' and new.status in ('draft','submitted'))
      or (old.status = 'editing' and new.status in ('editing','submitted'))
      or (old.status = 'approved' and new.status = 'edit_requested')
    ) then
      raise exception 'Invalid ship-officer study status transition: % -> %', old.status, new.status;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists aa_enforce_ship_study_update on public.sscs_studies;
create trigger aa_enforce_ship_study_update
before update on public.sscs_studies
for each row execute function public.enforce_ship_study_update();

-- ---------------------------------------------------------------------------
-- Lightweight audit triggers
-- ---------------------------------------------------------------------------
create or replace function public.audit_profile_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if old.account_status is distinct from new.account_status
     or old.role is distinct from new.role
     or old.is_admin is distinct from new.is_admin then
    insert into public.audit_logs(user_id, action, entity_type, entity_id, details)
    values (
      auth.uid(), 'profile_access_changed', 'profile', new.id::text,
      jsonb_build_object(
        'old_status', old.account_status, 'new_status', new.account_status,
        'old_role', old.role, 'new_role', new.role,
        'old_is_admin', old.is_admin, 'new_is_admin', new.is_admin
      )
    );
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists profiles_audit_trigger on public.profiles;
create trigger profiles_audit_trigger
before update on public.profiles
for each row execute function public.audit_profile_change();

create or replace function public.audit_study_status_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if old.status is distinct from new.status then
    insert into public.audit_logs(user_id, action, entity_type, entity_id, details)
    values (
      auth.uid(), 'study_status_changed', 'sscs_study', new.id,
      jsonb_build_object('old_status', old.status, 'new_status', new.status, 'vessel_id', new.vessel_id)
    );
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists studies_audit_trigger on public.sscs_studies;
create trigger studies_audit_trigger
before update on public.sscs_studies
for each row execute function public.audit_study_status_change();

create or replace function public.touch_vessel_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists vessels_touch_trigger on public.vessels;
create trigger vessels_touch_trigger
before update on public.vessels
for each row execute function public.touch_vessel_updated_at();

commit;
